### ISSUE TITLE
comlete画面 No Method Error 

### ISSUE THREAD

**Issue by HinakoKobayashi** [Team-C-Cacao/nagano-cake#106]
購入の流れやってみようとしたら、何だかエラーになってしまいました……

Showing /home/ec2-user/environment/nagano-cake/app/views/public/orders/complete.html.erb where line #6 raised:
undefined method `each' for nil:NilClass

Extracted source (around line #6):
 <%= @thanks.each do |item| %>

**Comment by Tsmore** [comment]
なおしましたー
