### ISSUE TITLE
各ビューファイルのテーブル関係

### ISSUE THREAD

**Issue by Tsmore** [Team-C-Cacao/nagano-cake#87]
theadを使っている方はクラス追加をお願いします。

adminはtable-secondary
`<thead class="table-secondary">`
publicはtable-warning
`<thead class="table-warning">`

**Comment by PikkaStar** [comment]
admin/customer/indexとadmin/order_detail/showのtableのthead記述完了しました

**Comment by Tsmore** [comment]
cartitems done
