### ISSUE TITLE
booleanでtrue,falseやってる方

### ISSUE THREAD

**Issue by Tsmore** [Team-C-Cacao/nagano-cake#88]
ビューファイルで真偽値で表示切り替えている方

trueの表記はstyle="color: #1a8066;
falseの表記はdanger

統一お願いします

**Comment by PikkaStar** [comment]
admin/customer/indexとadmin/customer/showのboolean表記完了しました

**Comment by Tsmore** [comment]
admin/itemsおーけー

**Comment by Tsmore** [comment]
閉じます
